version: '3.3'
services:
    linuxgsm-docker:
        container_name: cod4
        volumes:
            - 'cod4:/home/linuxgsm'
        ports:
            - '28960:28960/udp'
        network_mode: bridge
        restart: unless-stopped
        image: 'lov432/lgsm-cod4-docker:latest'

volumes:
  cod4:
    name: cod4
